- name: setup Action User
  user: generate_ssh_key=yes name={{action_user}} password={{action_user_pw | password_hash('sha512') }} shell=/bin/bash
- name: install docker
  command: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
- name: add deb repo
  command: sudo touch /etc/apt/sources.list.d/docker.list
- lineinfile: dest="/etc/apt/sources.list.d/docker.list" line="{{item}}"
  with_items:
    - "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
- name: apt update
  apt: update_cache=yes
- apt: name=docker-engine state=present
- name: Install docker compose
  command: curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- name: update permissions docker compose
  command: chmod +x /usr/local/bin/docker-compose
- name: add user mod
  command: sudo usermod -aG docker {{remote_user}}
- name: add user mod
  command: sudo usermod -aG docker {{action_user}}
- name: prepare folders
  command: mkdir -p /app/config && chown -R {{action_user}}: /app
- name: docker login
  command: docker login -u {{docker_user}} -p {{docker_password}}